# Generated by Django 6.0.7 on 2026-07-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_url', models.URLField(blank=True, verbose_name='External image URL (used if no image uploaded)')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, max_length=255, verbose_name='Place of work / institution')),
                ('interests', models.TextField(blank=True, verbose_name='Scientific interests')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile photo')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('doi', models.CharField(blank=True, max_length=500, verbose_name='DOI or URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Publication file (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.researcher')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
