# Generated by Django 6.1 on 2026-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_auto_imported',
            field=models.BooleanField(default=False, help_text='True if this item came from the RSS auto-fetch job.'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source_url',
            field=models.URLField(blank=True, help_text='Used to avoid importing the same RSS item twice.', verbose_name='Original article URL'),
        ),
    ]
