# Generated by Django 6.1 on 2026-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem_is_auto_imported_newsitem_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='category_logos/', verbose_name='Logo image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category logo',
                'verbose_name_plural': 'Category logos',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branding/', verbose_name='Site logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site logo',
                'verbose_name_plural': 'Site logo',
            },
        ),
    ]
