# Generated by Django 6.1 on 2026-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorylogo_sitebranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='Website URL')),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('impact_factor', models.CharField(blank=True, default='—', max_length=20)),
                ('desc', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='journal_logos/', verbose_name='Uploaded publisher logo')),
                ('logo_url', models.URLField(blank=True, help_text='Used if no file is uploaded above (e.g. a Wikimedia Commons link).', verbose_name='External publisher logo URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='Website URL')),
                ('desc', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='resource_logos/', verbose_name='Uploaded logo')),
                ('logo_url', models.URLField(blank=True, help_text='Used if no file is uploaded above (e.g. a Wikimedia Commons link).', verbose_name='External logo URL')),
                ('fallback_image', models.ImageField(blank=True, null=True, upload_to='resource_fallback/', verbose_name='Uploaded fallback photo')),
                ('fallback_image_url', models.URLField(blank=True, help_text='Shown only if no logo (file or URL) is set above.', verbose_name='External fallback photo URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
