# Generated by Django 6.1 on 2026-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journal_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='Website URL')),
                ('desc', models.TextField(help_text='What the company makes/does.', verbose_name='Description')),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Uploaded logo')),
                ('logo_url', models.URLField(blank=True, help_text='Used if no file is uploaded above.', verbose_name='External logo URL')),
                ('fallback_image', models.ImageField(blank=True, null=True, upload_to='company_fallback/', verbose_name='Uploaded fallback photo')),
                ('fallback_image_url', models.URLField(blank=True, help_text='Shown only if no logo (file or URL) is set above.', verbose_name='External fallback photo URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for a single-day event.', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=32)),
                ('desc', models.TextField(verbose_name='Description')),
                ('registration_url', models.URLField(blank=True, verbose_name='Registration / event page URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Uploaded image')),
                ('image_url', models.URLField(blank=True, help_text='Used if no file is uploaded above.', verbose_name='External image URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (ties broken by date).')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
