# Generated by Django 6.1 on 2026-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='logo',
            field=models.ImageField(blank=True, help_text="A photo of the journal's cover or title page (or a publisher logo) — shown as the card image, same style as the Resources page.", null=True, upload_to='journal_logos/', verbose_name='Cover / title page image'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Used if no file is uploaded above (e.g. a Wikimedia Commons link).', verbose_name='External cover / title page image URL'),
        ),
    ]
