# Generated by Django 6.0.8 on 2026-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_journal_logo_alter_journal_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_auto_imported',
            field=models.BooleanField(default=False, help_text='True if this event was pulled in automatically by the fetch_events job.'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the original listing this event was imported from (used to avoid duplicate imports). Left blank for manually-added events.', verbose_name='Original source URL'),
        ),
    ]
