# Generated by Django 6.0.8 on 2026-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_is_auto_imported_event_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='External image URL (used if no image uploaded)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source_url',
            field=models.URLField(blank=True, help_text='Used to avoid importing the same RSS item twice.', max_length=1000, verbose_name='Original article URL'),
        ),
    ]
