# Generated by Django 6.0.8 on 2026-09-07 15:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_newsitem_image_url_alter_newsitem_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fire Safety', 'Fire Safety'), ('CBRN', 'CBRN'), ('EOD', 'EOD'), ('Disaster Medicine', 'Disaster Medicine'), ('Environmental Safety', 'Environmental Safety')], max_length=512),
        ),
    ]
