"""
Django settings for irccp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Locally this falls back to the old hardcoded dev key so nothing changes for
# you. On a real host, set the SECRET_KEY environment variable instead.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-q+*@*gv9j$-)8r$6c(ye_m7xqf*bmsan(rv8bcnvt)076i5iqr',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Locally this defaults to True (unchanged). On a real host, set DEBUG=False
# in the environment.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Render (and some other hosts) expose the public hostname via this env var —
# pick it up automatically so you don't have to hardcode it.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'irccp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.category_choices',
                'core.context_processors.donate_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'irccp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Defaults to the local SQLite file, exactly as before. If a DATABASE_URL
# environment variable is set (e.g. when you attach a Render Postgres
# database), that's used instead — no code changes needed either way.

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # WhiteNoise serves static files directly from the app process — no
    # separate nginx/CDN needed, works out of the box on Render's free tier.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Media files (user uploads: avatars, publication files, news images, logos)
#
# IMPORTANT if you deploy to a host with an ephemeral filesystem (e.g.
# Render's free tier): anything saved here is wiped on every redeploy/
# restart/spin-down. For a quick free demo that's an acceptable trade-off;
# for uploads that need to actually stick around, point this at an
# S3-compatible bucket instead (see README "Деплой" section).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

# --- RSS news auto-import -------------------------------------------------
# See core/rss_config.py for the list of feeds and core/scheduler.py for how
# the periodic job is started. Set RSS_AUTO_FETCH = False to disable the
# background scheduler entirely (you can still run it manually with
# `python manage.py fetch_news`).
RSS_AUTO_FETCH = True
RSS_FETCH_INTERVAL_HOURS = 6

# --- Donate button ---------------------------------------------------------
# Points the navbar "Donate" button at your real payment page once you have
# one. Change via the DONATE_URL environment variable — no code edit needed.
# See README "Кнопка доната" for quick options (Buy Me a Coffee, Ko-fi,
# PayPal.me) that need no business verification and take ~5 minutes to set up.
DONATE_URL = os.environ.get('DONATE_URL', 'https://www.buymeacoffee.com/irccp')
